"""Copy the dashboard's UI (markup, styles, client scripts) into the Next.js app.

The original dashboard/ folder is the source for the UI; run this after changing it:
    python3 web/scripts/sync-from-dashboard.py
"""
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[2]
DASH, WEB = ROOT / 'dashboard', ROOT / 'web'

# Page markup: everything inside <body> except the script tags
src = (DASH / 'index.html').read_text()
body = src.split('<body data-builtin="true">', 1)[1]
body = body[:body.index('<script src="app.js">')].strip() + '\n'
(WEB / 'app' / 'dashboard.html').write_text(body)

# Styles
for name in ('styles.css', 'tailor.css', 'profiles.css'):
    shutil.copy(DASH / name, WEB / 'app' / name)

# Client scripts, bundled so they load in order after the page is interactive
app = (DASH / 'app.js').read_text()
start = "document.addEventListener('DOMContentLoaded', () => {"
end = """  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      closeAddJobModal();
      closeProfile();
    }
  });
});"""
assert app.count(start) == 1 and app.count(end) == 1, 'app.js init block changed; update this script'
app = app.replace(start, "// Called once the page is ready (see the end of this bundle)\nfunction initApp() {", 1)
app = app.replace(end, end[:-3] + '}', 1)

bundle = '\n\n'.join([
    '// Kairo dashboard client (app.js + tailor-ui.js + profiles-ui.js)\n// Generated by web/scripts/sync-from-dashboard.py - edit the files in dashboard/ instead.',
    app,
    (DASH / 'tailor-ui.js').read_text(),
    (DASH / 'profiles-ui.js').read_text(),
    """// Boot after every definition above exists
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initApp);
} else {
  initApp();
}
"""])
(WEB / 'public' / 'js' / 'kairo.js').write_text(bundle)
print('Synced dashboard UI into web/')
